-- any sql that is to be pre-loaded before testsuite runs goes in here
-- statements must be a single line without returns
DROP TABLE PLATFORM_USER IF EXISTS
DROP TABLE MEMBER IF EXISTS

CREATE TABLE PLATFORM_USER (ID INTEGER IDENTITY NOT NULL, PWHASH VARCHAR, USERNAME VARCHAR, VERSION INTEGER, CREATED_DATE DATETIME, UPDATED_DATE DATETIME, PRIMARY KEY (ID))
CREATE TABLE MEMBER (ID INTEGER IDENTITY NOT NULL, MEMBEREMAIL VARCHAR,MEMBERFIRSTNAME VARCHAR, MEMBERLASTNAME VARCHAR, MEMBERPHONE VARCHAR,VERSION INTEGER, CREATED_DATE TIMESTAMP, UPDATED_DATE TIMESTAMP, PLATFORMUSER_ID INTEGER, CONSTRAINT CONSTRAINT_8 PRIMARY KEY (ID), CONSTRAINT FK_MEMBER_PLATFORMUSER_ID FOREIGN KEY (PLATFORMUSER_ID) REFERENCES PLATFORM_USER(ID) ON DELETE RESTRICT ON UPDATE RESTRICT)
